### ISSUE TITLE
Jakk's master TODO list.

### ISSUE THREAD

**Issue by Jakksergal** [Jakksergal/VOREStation#1]
- [x] Red Armory is walled off, literally.
- [x] step_x/y is != 0 somewhere.
- [x] Bathroom poorly lit
- [x] Visitation poorly lit
- [x] Security EVA and substation doors do not have lockdown shutters.
- [x] Security EVA lacks tanks
- [x] Visitation lacks windoors
- [x] IAA cannot access main halls past first door.
- [x] IAA cannot access break room or restroom
- [x] IAA cannot access evidence storage
- [x] IAA cannot access visitation
- [x] EVA has no access requirements
- [x] Cell timers do not function
- [x] Certain rusts in rec closet do not color properly
- [x] Warden does not have access to the armory even during code red. The fuck.
- [x] Missing 3 E-guns in blue armory
- [x] Missing wire in riot control
- [x] Many blast door buttons are missing still
- [ ] 
- [x] Lobby blast doors can be inverted somehow? Needs testing.
